# Workflow to build at each commit in master the application

name: CI build quizz app

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can noaccess it
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.1' # The Go version to download (if necessary) and use.
    # Build the back
    - name: Build go server for RPi
      run: |
        echo Run build server go
        cd src/main
        export GOOS=linux
        export GOARCH=arm
        go build -o quizz_server run_quizz.go
        cd ../../
        mkdir artifacts
        echo Copy server artifact in artifacts/
        mv src/main/quizz_server artifacts

      # Build the front
    - name: Build front
      run: |
        echo Install and build app,
        cd resources
        npm install
        npm run-script build
        tar -cvzf build.tar.gz build
        mv build.tar.gz ../artifacts

    # Upload artifact
    - uses: actions/upload-artifact@v4
      with:
        name: Artifacts quizz app
        path: artifacts
